### ISSUE TITLE
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String if a world name is only numbers

### ISSUE THREAD

**Issue by Chew** [Angeschossen/Lands#18]
Hello there!

I was helping a user who was having an issue loading this plugin. The exact error being:

```
[11:36:58] [Server thread/INFO]: [Lands] Enabling Lands v5.1.4
[11:36:58] [Server thread/WARN]: [Lands] [Config] You have a YML format mistake in your config. Issues might occur. THIS IS NOT A LANDS ISSUE. Option: general.claim-worlds
[11:36:58] [Server thread/WARN]: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
[11:36:58] [Server thread/WARN]: 	at me.angeschossen.lands.nsVkS.baZfj.iTKsj.iTKsj(?:609)
[11:36:58] [Server thread/WARN]: 	at me.angeschossen.lands.NtOK.iTKsj.DbNVf(?:59)
[11:36:58] [Server thread/WARN]: 	at me.angeschossen.lands.nsVkS.baZfj.iTKsj.iTKsj(?:243)
[11:36:58] [Server thread/WARN]: 	at me.angeschossen.lands.NtOK.iTKsj.NtOK(?:49)
[11:36:58] [Server thread/WARN]: 	at me.angeschossen.lands.nsVkS.baZfj.iTKsj.NtOK(?:262)
[11:36:58] [Server thread/WARN]: 	at me.angeschossen.lands.nsVkS.baZfj.iTKsj.iTKsj(?:605)
[11:36:58] [Server thread/WARN]: 	at me.angeschossen.lands.NtOK.iTKsj.iTKsj(?:46)
[11:36:58] [Server thread/WARN]: 	at me.angeschossen.lands.Lands.onEnable(?:180)
[11:36:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:36:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[11:36:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[11:36:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
[11:36:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
[11:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435)
[11:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218)
[11:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809)
[11:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[11:36:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

Although it does say, "THIS IS NOT A LANDS ISSUE," this technically is. What happened was their world name was literally the number 1, so it was attempting to be parsed as a number instead of a string, causing loading to fail. Changing `1` to `"1"` might fix the issue, but I've yet to receive if the issue has been resolved properly.

Additionally, the comments suggest you reload the server to reload the config. This is highly not recommended and should never be suggested.

Sadly, this plugin violates Bukkit's GPLv3 license, so I cannot fix this issue myself. A simple `String.valueOf(input)` should fix it right up. So sadly, I have to report it here. Sad to see yet another premium plugin violate the license, but alas, that's simply the world we live in.

**Comment by Angeschossen** [comment]
Thanks for reporting! Fixed in next :)
