### ISSUE TITLE
FATAL ERROR ISSUE

### ISSUE THREAD

**Issue by EndeBy** [Angeschossen/Lands#3]
i gave this in console: [01:56:02] [Server thread/INFO]: EndeSP issued server command: /lands
[01:56:02] [Server thread/WARN]: java.lang.NullPointerException
[01:56:02] [Server thread/WARN]: 	at me.angeschossen.lands.a.s.a(SourceFile:35)
[01:56:02] [Server thread/WARN]: 	at me.angeschossen.lands.a.a.a.onCommand(SourceFile:181)
[01:56:02] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:56:02] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[01:56:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
[01:56:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:333)
[01:56:02] [Server thread/WARN]: 	at me.angeschossen.lands.a.a.a.onCommand(SourceFile:136)
[01:56:02] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:56:02] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[01:56:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887)
[01:56:02] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820)
[01:56:02] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

An this ingame: http://prntscr.com/okxroj

**Comment by Angeschossen** [comment]
Hey,

seems BlackSpigot, or whereever you downloaded this illegal version of Lands, does not use latest.

**Comment by Angeschossen** [comment]
Hello,

It seems like you're using a outdated version. Please join our Discord to get more support on this:
https://discord.gg/B4MAJVk
